model_name_or_path: "path_to_38b_model"
output_dir: "../output"
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
num_train_epochs: 2
learning_rate: 2e-5
logging_steps: 10
save_steps: 1000
max_seq_length: 2048
deepspeed: "../configs/ds_config.json"
fp16: true
bf16: false
gradient_checkpointing: true
resume_from_checkpoint: null
eval_steps: 2000
evaluation_strategy: "steps"
save_total_limit: 3
logging_dir: "../output/logs"